name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # ou a versão que você está utilizando

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run --spec 'cypress/e2e/instagram_testes.spec.js'
        env:
          CYPRESS_BASE_URL: 'http://localhost:3000' # ajuste para sua URL de teste

      - name: Upload Cypress videos and screenshots
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: cypress/videos/**, cypress/screenshots/**
